include ActionDispatch::TestProcess

def avatar(who)
  fixture_file_upload("#{Rails.root}/spec/fixtures/#{who}.jpg", 'img/jpg')
end

puts 'woloxers'

conco = User.create!(name: 'Conco', avatar: avatar('conco'), is_admin: true, email: 'cmaderblanco@wolox.com.ar', password: 'password', password_confirmation: 'password')
nacho = User.create!(name: 'Nacho', avatar: avatar('nacho'), is_admin: true, email: 'ignacio.rivera@wolox.com.ar')
bermu = User.create!(name: 'Santi Bermudez', avatar: avatar('bermu'), email: 'santiago.baglietto@wolox.com.ar')
wilson = User.create!(name: 'Wilson', avatar: avatar('wilson'), email: 'williams.matias@wolox.com.ar')
rampa = User.create!(name: 'Rampa', avatar: avatar('rampa'), email: 'santiago.samra@wolox.com.ar')
nixon = User.create!(name: 'Nixon', avatar: avatar('nixon'), email: 'nicomagni@wolox.com.ar')
pol = User.create!(name: 'Pol', avatar: avatar('pol'), email: 'pablo.giorgi@wolox.com.ar')
lula = User.create!(name: 'Lula', avatar: avatar('lula'), email: 'zeminlu@wolox.com.ar')
guido = User.create!(name: 'Guido', avatar: avatar('guido'), email: 'guidomb@wolox.com.ar')
mds = User.create!(name: 'Mati De Santi', avatar: avatar('mds'), email: 'matias.desanti@wolox.com.ar')
ita = User.create!(name: 'Ita', avatar: avatar('ita'), email: 'esteban.pintos@wolox.com.ar')
fagus = User.create!(name: 'Fagus', avatar: avatar('fagus'), email: 'agustina.fainguersch@wolox.com.ar')
fefe = User.create!(name: 'Fefe R', avatar: avatar('fefe'), email: 'federico.ramundo@wolox.com.ar')
chino = User.create!(name: 'Chino', avatar: avatar('chino'), email: 'jose.galindo@wolox.com.ar')
luqui = User.create!(name: 'Luqui', avatar: avatar('luqui'), email: 'lucas.moscovicz@wolox.com.ar')
buch = User.create!(name: 'Buchhalter', avatar: avatar('buch'), email: 'nicolas.buchhalter@wolox.com.ar')
fefo = User.create!(name: 'Fefo H', avatar: avatar('fefo'), email: 'federico.homovc@wolox.com.ar')
leo = User.create!(name: 'Leo', avatar: avatar('leo'), email: 'leonel.badi@wolox.com.ar')
jp = User.create!(name: 'JP', avatar: avatar('jp'), email: 'jpdelorenzo@wolox.com.ar')
ninja = User.create!(name: 'Ninja', avatar: avatar('ninja'), email: 'mariano.matayoshi@wolox.com.ar')
gon = User.create!(name: 'Gonzalo', avatar: avatar('gon'), email: 'gonzalo.garcia@wolox.com.ar')
germu = User.create!(name: 'German (Pancet)', avatar: avatar('germu'), email: 'german.romarion@wolox.com.ar')
tedin = User.create!(name: 'Federico Virgilio Tedin', email: 'federico.tedin@wolox.com.ar')
euge = User.create!(name: 'Euge (Princess)', avatar: avatar('euge'), email: 'eugenia.lago@wolox.com.ar')
ana = User.create!(name: 'Anabella', avatar: avatar('ana'), email: 'anabella.mazzuca@wolox.com.ar')
fran = User.create!(name: 'Fran', email: 'francisco.cervellera@wolox.com.ar')
lule = User.create!(name: 'Lule Rez', avatar: avatar('lule'), email: 'luciana.reznik@wolox.com.ar')
sola = User.create!(name: 'Fer Sola', avatar: avatar('sola'), email: 'fernando.sola@wolox.com.ar')
dani = User.create!(name: 'Dani', avatar: avatar('dani'), email: 'daniela.martin@wolox.com.ar')
mati_a = User.create!(name: 'Mati A', avatar: avatar('mati_a'), email: 'matias.alvarez@wolox.com.a')
dinu = User.create!(name: 'Di Nucci', avatar: avatar('dinu'), email: 'federico.dinucci@wolox.com.ar')
shiz = User.create!(name: 'Shizus', avatar: avatar('shiz'), email: 'jesus.herrera@wolox.com.ar')
inaki = User.create!(name: 'Iñaki', avatar: avatar('inaki'), email: 'inaki.lanusse@wolox.com.ar')
agulo = User.create!(name: 'Agulo', avatar: avatar('agulo'), email: 'agustin.pagnoni@wolox.com.ar')
zannini = User.create!(name: 'Franco Zaninni', avatar: avatar('zannini'), email: 'franco.zannini@wolox.com.ar')
anita = User.create!(name: 'Anita', avatar: avatar('anita'), email: 'anita.romero@wolox.com.ar')
tylson = User.create!(name: 'Emilio Tylson', avatar: avatar('tylson'), email: 'emilio.tylson@wolox.com.ar')
seba = User.create!(name: 'Seba B', avatar: avatar('seba'), email: 'sebastian.balay@wolox.com.ar')
ferro = User.create!(name: 'Pablito Ferro', email: 'pablo.ferro@wolox.com.ar')
capi = User.create!(name: 'Capi', avatar: avatar('capi'), email: 'dfinkelstein@wolox.com.ar')
lu = User.create!(name: 'Lu S', avatar: avatar('lu'), email: 'lucila.stancato@wolox.com.ar')
gabo = User.create!(name: 'Gabo', avatar: avatar('gabo'), email: 'gabriel.zanzoti@wolox.com.ar')
tomy = User.create!(name: 'Tomy', avatar: avatar('tomy'), email: 'tomas.mehdi@wolox.com.ar')
negri = User.create!(name: 'Javo (Negri)', avatar: avatar('negri'), email: 'javier.fraire@wolox.com.ar')
ranti = User.create!(name: 'Ranti', avatar: avatar('ranti'), email: 'santiago.roldan@wolox.com.ar')
michel = User.create!(name: 'Mishu', avatar: avatar('michel'), email: 'michel.agopian@wolox.com.ar')

puts 'categories'
moises = Category.create!(image: avatar('moises'), title: 'El W-Moises', description: 'Quien es el mas judio de Wolox??')
chef = Category.create!(image: avatar('chef'), title: 'El Chef Wolox', description: 'Quien es el mejor cocinero de Wolox?')
peor_lava = Category.create!(image: avatar('peor_lava'), title: 'El que peor lava', description: 'Quien es el que peor lava de Wolox??')
# ortiva = Category.create!(image: avatar('ortiva'), title: 'El W-Ortiva', description: 'Quien se pone la gorra?')
embudo = Category.create!(image: avatar('embudo'), title: 'El premio embudo!', description: 'El mas roto del año')
bullied = Category.create!(image: avatar('bullied'), title: 'El W-Bowling', description: 'La victima de bullying')
bully = Category.create!(image: avatar('bully'), title: 'El W-Bowler', description: 'El ejecutor del bullying')
giladita = Category.create!(image: avatar('giladita'), title: 'W-Giladita', description: 'El mas fit en la barra de dominadas')
log = Category.create!(image: avatar('log'), title: 'El peor time-logger', description: 'El frequent flyer de NO loggear las horas')
pasto = Category.create!(image: avatar('pasto'), title: 'El W-Pasto', description: 'El jardinero')
fantasma = Category.create!(image: avatar('fantasma'), title: 'El W-Fantasma', description: 'El q menos vino')
# rumor = Category.create!(image: avatar('rumor'), title: 'El premio embudo!', description: 'El mas roto del año')
jodafb = Category.create!(image: avatar('jodafb'), title: 'La W-joda-Facebook', description: 'La victima de la peor joda de Facebook')
trolfb = Category.create!(image: avatar('trolfb'), title: 'El W-Trol-Facebook', description: 'La ejecutor de la peor joda de Facebook')
calenton = Category.create!(image: avatar('calenton'), title: 'El W-Calenton', description: 'Much Angry Such Rage')
rustic = Category.create!(image: avatar('rustic'), title: 'El W-rustico', description: 'El mas rustiq en el Wfootball')
lyric = Category.create!(image: avatar('lyric'), title: 'El W-lirico', description: 'El mas lyric en el Wfootball')

wdj = Category.create!(image: avatar('wdj'), title: 'El WDJ', description: 'Such Music, Wow, Very Hear')
closet = Category.create!(image: avatar('closet'), title: 'El W-Closet', description: "La revelación del año.")
fabuloso = Category.create!(image: avatar('fabuloso'), title: 'El W-Fabulous', description: 'El mas chic')
tribu = Category.create!(image: avatar('tribu'), title: 'El W-tribu', description: 'Quien es el alma de la tribu?', is_closed_to_nominate: true)
ctaptc = Category.create!(image: avatar('ctaptc'), title: 'El CTAPTC', description: 'wwww.todotartas.com.ar', is_closed_to_nominate: true)
police = Category.create!(image: avatar('police'), title: 'La W-police', description: 'La yuta loco')
malaonda = Category.create!(image: avatar('malaonda'), title: 'EL W-MalaOnda', description: 'Menos onda que y = a*x + b')
bebu = Category.create!(image: avatar('bebu'), title: 'El Premio Bebu', description: 'El mejor apodo')
conqueada = Category.create!(image: avatar('conqueada'), title: 'La Conqueada de Oro', description: 'Quien es mas torpe/inutil')
barrilete = Category.create!(image: avatar('barrilete'), title: 'El W-barrilete', description: 'Este no se que quiere decir pero estaba anotado en el pizarron')
promiscuo = Category.create!(image: avatar('promiscuo'), title: 'El W-promiscuo', description: 'Quien revolea la chancleta?')
futbol = Category.create!(image: avatar('futbol'), title: 'El W-futbolero', description: 'Quien es el lider del mejor equipo (Tribu / Others)', is_closed_to_nominate: true)
companiero = Category.create!(image: avatar('companiero'), title: 'El W-Compañero', description: 'Quien es infalible? <3')
tl = Category.create!(image: avatar('tl'), title: 'El W-TL de Oro', description: 'Que TL la pisa mas?', is_closed_to_nominate: true)
po = Category.create!(image: avatar('po'), title: 'El W-PO de Oro', description: 'Que PO es el mas mejor?', is_closed_to_nominate: true)
founder = Category.create!(image: avatar('founder'), title: 'El W-founder', description: 'Quien es tu founder preferido?', is_closed_to_nominate: true)
nuevo = Category.create!(image: avatar('nuevo'), title: 'El W-nuevo', description: 'Quien es tu nuevo preferido (2014)?', is_closed_to_nominate: true)

oro = Category.create!(image: avatar('oro'), title: 'El Woloxer de Oro!', description: 'Quien es el mejor woloxer?')

puts 'nominees'
Nominee.create!(user: fagus, category: moises)
Nominee.create!(user: luqui, category: moises)
Nominee.create!(user: capi, category: moises)
Nominee.create!(user: lule, category: moises)
Nominee.create!(user: nacho, category: chef)
Nominee.create!(user: lu, category: chef)
Nominee.create!(user: lula, category: chef)
Nominee.create!(user: conco, category: chef)
Nominee.create!(user: conco, category: peor_lava)
Nominee.create!(user: tomy, category: peor_lava)
# Nominee.create!(user: mati_a, category: ortiva)
# Nominee.create!(user: ninja, category: ortiva)
# Nominee.create!(user: bermu, category: ortiva)
# Nominee.create!(user: mds, category: ortiva)
Nominee.create!(user: negri, category: embudo)
Nominee.create!(user: shiz, category: embudo)
Nominee.create!(user: negri, category: bullied)
Nominee.create!(user: conco, category: bullied)
Nominee.create!(user: chino, category: bullied)
Nominee.create!(user: conco, category: bully)
Nominee.create!(user: nixon, category: bullied)
Nominee.create!(user: gabo, category: giladita)
Nominee.create!(user: buch, category: giladita)
Nominee.create!(user: luqui, category: giladita)
Nominee.create!(user: jp, category: giladita)
Nominee.create!(user: fran, category: giladita)
Nominee.create!(user: ranti, category: giladita)
Nominee.create!(user: fefe, category: log)
Nominee.create!(user: nacho, category: log)
Nominee.create!(user: fefe, category: pasto)
Nominee.create!(user: lu, category: pasto)
Nominee.create!(user: conco, category: pasto)
Nominee.create!(user: anita, category: pasto)
Nominee.create!(user: nixon, category: pasto)
Nominee.create!(user: conco, category: jodafb)
Nominee.create!(user: euge, category: jodafb)
Nominee.create!(user: lu, category: jodafb)
Nominee.create!(user: nixon, category: jodafb)
Nominee.create!(user: conco, category: trolfb)
Nominee.create!(user: fefe, category: trolfb)
Nominee.create!(user: jp, category: trolfb)
Nominee.create!(user: mds, category: calenton)
Nominee.create!(user: negri, category: calenton)
Nominee.create!(user: wilson, category: calenton)
Nominee.create!(user: conco, category: rustic)
Nominee.create!(user: tomy, category: rustic)
Nominee.create!(user: nixon, category: rustic)
Nominee.create!(user: luqui, category: lyric)
Nominee.create!(user: agulo, category: lyric)
Nominee.create!(user: jp, category: lyric)
Nominee.create!(user: seba, category: lyric)
Nominee.create!(user: nacho, category: wdj)
Nominee.create!(user: nixon, category: wdj)
Nominee.create!(user: mds, category: wdj)
Nominee.create!(user: lula, category: wdj)
Nominee.create!(user: fefe, category: fabuloso)
Nominee.create!(user: euge, category: fabuloso)
Nominee.create!(user: chino, category: fabuloso)
Nominee.create!(user: fagus, category: tribu)
Nominee.create!(user: agulo, category: tribu)
Nominee.create!(user: gabo, category: tribu)
Nominee.create!(user: inaki, category: tribu)
Nominee.create!(user: luqui, category: tribu)
Nominee.create!(user: conco, category: tribu)
Nominee.create!(user: fagus, category: ctaptc)
Nominee.create!(user: euge, category: ctaptc)
Nominee.create!(user: anita, category: police)
Nominee.create!(user: wilson, category: police)
Nominee.create!(user: wilson, category: malaonda)
Nominee.create!(user: mds, category: malaonda)
Nominee.create!(user: rampa, category: malaonda)
Nominee.create!(user: guido, category: malaonda)
Nominee.create!(user: gabo, category: bebu)
Nominee.create!(user: negri, category: bebu)
Nominee.create!(user: germu, category: bebu)
Nominee.create!(user: conco, category: conqueada)
Nominee.create!(user: tomy, category: conqueada)
Nominee.create!(user: euge, category: promiscuo)
Nominee.create!(user: capi, category: futbol)
Nominee.create!(user: jp, category: futbol)
Nominee.create!(user: conco, category: tl)
Nominee.create!(user: nixon, category: tl)
Nominee.create!(user: fefe, category: tl)
Nominee.create!(user: pol, category: tl)
Nominee.create!(user: ita, category: tl)
Nominee.create!(user: mds, category: tl)
Nominee.create!(user: bermu, category: fantasma)
Nominee.create!(user: mds, category: fantasma)
Nominee.create!(user: ninja, category: fantasma)
Nominee.create!(user: mati_a, category: fantasma)
Nominee.create!(user: conco, category: po)
Nominee.create!(user: nacho, category: po)
Nominee.create!(user: nixon, category: po)
Nominee.create!(user: lula, category: po)
Nominee.create!(user: rampa, category: po)
Nominee.create!(user: rampa, category: founder)
Nominee.create!(user: nixon, category: founder)
Nominee.create!(user: wilson, category: founder)
Nominee.create!(user: bermu, category: founder)
Nominee.create!(user: guido, category: founder)
Nominee.create!(user: lula, category: founder)
Nominee.create!(user: pol, category: founder)

Nominee.create!(user: buch, category: nuevo)
Nominee.create!(user: tylson, category: nuevo)
Nominee.create!(user: leo, category: nuevo)
Nominee.create!(user: michel, category: nuevo)
Nominee.create!(user: gon, category: nuevo)
Nominee.create!(user: tedin, category: nuevo)
Nominee.create!(user: germu, category: nuevo)
Nominee.create!(user: negri, category: nuevo)
Nominee.create!(user: dinu, category: nuevo)
Nominee.create!(user: tomy, category: nuevo)
Nominee.create!(user: ranti, category: nuevo)
Nominee.create!(user: sola, category: nuevo)
Nominee.create!(user: lule, category: nuevo)
Nominee.create!(user: anita, category: nuevo)
Nominee.create!(user: ana, category: nuevo)
Nominee.create!(user: zannini, category: nuevo)
Nominee.create!(user: ferro, category: nuevo)
Nominee.create!(user: euge, category: nuevo)

puts 'done :)'