# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or create!d alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create!([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create!(name: 'Emanuel', city: cities.first)
# encoding: utf-8

puts 'woloxers'

conco = User.create!(name: 'Conco', is_admin: true, email: 'cmaderblanco@wolox.com.ar', password: 'password', password_confirmation: 'password')
nacho = User.create!(name: 'Nacho', is_admin: true, email: 'ignacio.rivera@wolox.com.ar', password: 'password', password_confirmation: 'password')
bermu = User.create!(name: 'Santi Bermudez', email: 'santiago.baglietto@wolox.com.ar', password: 'password', password_confirmation: 'password')
wilson = User.create!(name: 'Wilson', email: 'williams.matias@wolox.com.ar', password: 'password', password_confirmation: 'password')
rampa = User.create!(name: 'Rampa', email: 'santiago.samra@wolox.com.ar', password: 'password', password_confirmation: 'password')
nixon = User.create!(name: 'Nixon', email: 'nicomagni@wolox.com.ar', password: 'password', password_confirmation: 'password')
pol = User.create!(name: 'Pol', email: 'pablo.giorgi@wolox.com.ar', password: 'password', password_confirmation: 'password')
lula = User.create!(name: 'Lula', email: 'zeminlu@wolox.com.ar', password: 'password', password_confirmation: 'password')
guido = User.create!(name: 'Guido', email: 'guidomb@wolox.com.ar', password: 'password', password_confirmation: 'password')
mds = User.create!(name: 'Mati De Santi', email: 'matias.desanti@wolox.com.ar', password: 'password', password_confirmation: 'password')
ita = User.create!(name: 'Ita', email: 'esteban.pintos@wolox.com.ar', password: 'password', password_confirmation: 'password')
fagus = User.create!(name: 'Fagus', email: 'agustina.fainguersch@wolox.com.ar', password: 'password', password_confirmation: 'password')
fefe = User.create!(name: 'Fefe R', email: 'federico.ramundo@wolox.com.ar', password: 'password', password_confirmation: 'password')
chino = User.create!(name: 'Chino', email: 'jose.galindo@wolox.com.ar', password: 'password', password_confirmation: 'password')
luqui = User.create!(name: 'Luqui', email: 'lucas.moscovicz@wolox.com.ar', password: 'password', password_confirmation: 'password')
buch = User.create!(name: 'Buchhalter', email: 'nicolas.buchhalter@wolox.com.ar', password: 'password', password_confirmation: 'password')
fefo = User.create!(name: 'Fefo H', email: 'federico.homovc@wolox.com.ar', password: 'password', password_confirmation: 'password')
leo = User.create!(name: 'Leo', email: 'leonel.badi@wolox.com.ar', password: 'password', password_confirmation: 'password')
jp = User.create!(name: 'JP', email: 'jpdelorenzo@wolox.com.ar', password: 'password', password_confirmation: 'password')
ninja = User.create!(name: 'Ninja', email: 'mariano.matayoshi@wolox.com.ar', password: 'password', password_confirmation: 'password')
gon = User.create!(name: 'Gonzalo', email: 'gonzalo.garcia@wolox.com.ar', password: 'password', password_confirmation: 'password')
germu = User.create!(name: 'German (Pancet)', email: 'german.romarion@wolox.com.ar', password: 'password', password_confirmation: 'password')
tedin = User.create!(name: 'Federico Virgilio Tedin', email: 'federico.tedin@wolox.com.ar', password: 'password', password_confirmation: 'password')
euge = User.create!(name: 'Euge (Princess)', email: 'eugenia.lago@wolox.com.ar', password: 'password', password_confirmation: 'password')
ana = User.create!(name: 'Anabella', email: 'anabella.mazzuca@wolox.com.ar', password: 'password', password_confirmation: 'password')
fran = User.create!(name: 'Fran', email: 'francisco.cervellera@wolox.com.ar', password: 'password', password_confirmation: 'password')
lule = User.create!(name: 'Lule Rez', email: 'luciana.reznik@wolox.com.ar', password: 'password', password_confirmation: 'password')
sola = User.create!(name: 'Fer Sola', email: 'fernando.sola@wolox.com.ar', password: 'password', password_confirmation: 'password')
dani = User.create!(name: 'Dani', email: 'daniela.martin@wolox.com.ar', password: 'password', password_confirmation: 'password')
mati_a = User.create!(name: 'Mati A', email: 'matias.alvarez@wolox.com.a', password: 'password', password_confirmation: 'password')
dinu = User.create!(name: 'Di Nucci', email: 'federico.dinucci@wolox.com.ar', password: 'password', password_confirmation: 'password')
shiz = User.create!(name: 'Shizus', email: 'jesus.herrera@wolox.com.ar', password: 'password', password_confirmation: 'password')
inaki = User.create!(name: 'Iñaki', email: 'inaki.lanusse@wolox.com.ar', password: 'password', password_confirmation: 'password')
agulo = User.create!(name: 'Agulo', email: 'agustin.pagnoni@wolox.com.ar', password: 'password', password_confirmation: 'password')
zannini = User.create!(name: 'Franco Z', email: 'franco.zannini@wolox.com.ar', password: 'password', password_confirmation: 'password')
anita = User.create!(name: 'Anita', email: 'anita.romero@wolox.com.ar', password: 'password', password_confirmation: 'password')
tylson = User.create!(name: 'Emilio Tylson', email: 'emilio.tylson@wolox.com.ar', password: 'password', password_confirmation: 'password')
seba = User.create!(name: 'Seba B', email: 'sebastian.balay@wolox.com.ar', password: 'password', password_confirmation: 'password')
ferro = User.create!(name: 'Pablito Ferro', email: 'pablo.ferro@wolox.com.ar', password: 'password', password_confirmation: 'password')
max = User.create!(name: 'Maxi', email: 'maximiliano.schultheis@wolox.com.ar', password: 'password', password_confirmation: 'password')
capi = User.create!(name: 'Capi', email: 'dfinkelstein@wolox.com.ar', password: 'password', password_confirmation: 'password')
lu = User.create!(name: 'Lu S', email: 'lucila.stancato@wolox.com.ar', password: 'password', password_confirmation: 'password')
gabo = User.create!(name: 'Gabo', email: 'gabriel.zanzoti@wolox.com.ar', password: 'password', password_confirmation: 'password')
tomy = User.create!(name: 'Tomy', email: 'tomas.mehdi@wolox.com.ar', password: 'password', password_confirmation: 'password')
fepo = User.create!(name: 'Fepo', email: 'federico.pomar@wolox.com.ar', password: 'password', password_confirmation: 'password')
negri = User.create!(name: 'Javo (Negri)', email: 'javier.fraire@wolox.com.ar', password: 'password', password_confirmation: 'password')
ranti = User.create!(name: 'Ranti', email: 'santiago.roldan@wolox.com.ar', password: 'password', password_confirmation: 'password')

puts 'categories'
moises = Category.create!(title: 'El W-Moises', description: 'Quien es el mas judio de Wolox??')
chef = Category.create!(title: 'El Chef Wolox', description: 'Quien es el mejor cocinero de Wolox?')
peor_lava = Category.create!(title: 'El que peor lava', description: 'Quien es el que peor lava de Wolox??')
# ortiva = Category.create!(title: 'El W-Ortiva', description: 'Quien se pone la gorra?')
embudo = Category.create!(title: 'El premio embudo!', description: 'El mas roto del año')
bullied = Category.create!(title: 'El W-Bowling', description: 'La victima de bullying')
bully = Category.create!(title: 'El W-Bowler', description: 'El ejecutor del bullying')
giladita = Category.create!(title: 'W-Giladita', description: 'El mas fit en la barra de dominadas')
log = Category.create!(title: 'El peor time-logger', description: 'El frequent flyer de NO loggear las horas')
pasto = Category.create!(title: 'El W-Pasto', description: 'El jardinero')
fantasma = Category.create!(title: 'El W-Fantasma', description: 'El q menos vino')

# rumor = Category.create!(title: 'El premio embudo!', description: 'El mas roto del año')
jodafb = Category.create!(title: 'La W-joda-Facebook', description: 'La victima de la peor joda de Facebook')
trolfb = Category.create!(title: 'El W-Trol-Facebook', description: 'La ejecutor de la peor joda de Facebook')
calenton = Category.create!(title: 'El W-Calenton', description: 'Much Angry Such Rage')
rustic = Category.create!(title: 'El W-rustico', description: 'El mas rustiq en el Wfootball')
lyric = Category.create!(title: 'El W-lirico', description: 'El mas lyric en el Wfootball')

wdj = Category.create!(title: 'El WDJ', description: 'Such Music, Wow, Very Hear')
closet = Category.create!(title: 'El W-Closet', description: "La revelación del año.\nXOXO Gossip Girl")
fabuloso = Category.create!(title: 'El W-Fabulous', description: 'El mas chic')
tribu = Category.create!(title: 'El W-tribu', description: 'Quien es el alma de la tribu?', is_closed_to_nominate: true)
ctaptc = Category.create!(title: 'El CTAPTC', description: 'wwww.todotartas.com.ar', is_closed_to_nominate: true)
police = Category.create!(title: 'La W-police', description: 'La yuta loco')
malaonda = Category.create!(title: 'EL W-MalaOnda', description: 'Menos onda que y = a*x + b')
bebu = Category.create!(title: 'El Premio Bebu', description: 'El mejor apodo')
conqueada = Category.create!(title: 'La Conqueada de Oro', description: 'Quien es mas torpe/inutil')
barrilete = Category.create!(title: 'El W-barrilete', description: 'Este no se que quiere decir pero estaba anotado en el pizarron')
promiscuo = Category.create!(title: 'El W-promiscuo', description: 'Quien revolea la chancleta?')
futbol = Category.create!(title: 'El W-futbolero', description: 'Quien es el lider del mejor equipo (Tribu / Others)', is_closed_to_nominate: true)
companiero = Category.create!(title: 'El W-Compañero', description: 'Quien es infalible? <3')
tl = Category.create!(title: 'El W-TL de Oro', description: 'Que TL la pisa mas?', is_closed_to_nominate: true)
po = Category.create!(title: 'El W-PO de Oro', description: 'Que PO es el mas mejor?', is_closed_to_nominate: true)
founder = Category.create!(title: 'El W-founder', description: 'Quien es tu founder preferido?', is_closed_to_nominate: true)
nuevo = Category.create!(title: 'El W-nuevo', description: 'Quien es tu nuevo preferido (2014)?', is_closed_to_nominate: true)

oro = Category.create!(title: 'El Woloxer de Oro!', description: 'Quien es el mejor woloxer?')

puts 'nominees'
Nominee.create!(user: fagus, category: moises)
Nominee.create!(user: luqui, category: moises)
Nominee.create!(user: capi, category: moises)
Nominee.create!(user: lule, category: moises)
Nominee.create!(user: nacho, category: chef)
Nominee.create!(user: lu, category: chef)
Nominee.create!(user: lula, category: chef)
Nominee.create!(user: conco, category: chef)
Nominee.create!(user: conco, category: peor_lava)
Nominee.create!(user: tomy, category: peor_lava)
# Nominee.create!(user: mati_a, category: ortiva)
# Nominee.create!(user: ninja, category: ortiva)
# Nominee.create!(user: bermu, category: ortiva)
# Nominee.create!(user: mds, category: ortiva)
Nominee.create!(user: negri, category: embudo)
Nominee.create!(user: shiz, category: embudo)
Nominee.create!(user: negri, category: bullied)
Nominee.create!(user: conco, category: bullied)
Nominee.create!(user: chino, category: bullied)
Nominee.create!(user: conco, category: bully)
Nominee.create!(user: nixon, category: bullied)
Nominee.create!(user: gabo, category: giladita)
Nominee.create!(user: buch, category: giladita)
Nominee.create!(user: luqui, category: giladita)
Nominee.create!(user: jp, category: giladita)
Nominee.create!(user: fran, category: giladita)
Nominee.create!(user: ranti, category: giladita)
Nominee.create!(user: fefe, category: log)
Nominee.create!(user: nacho, category: log)
Nominee.create!(user: fepo, category: log)
Nominee.create!(user: fefe, category: pasto)
Nominee.create!(user: lu, category: pasto)
Nominee.create!(user: conco, category: pasto)
Nominee.create!(user: anita, category: pasto)
Nominee.create!(user: nixon, category: pasto)
Nominee.create!(user: conco, category: jodafb)
Nominee.create!(user: euge, category: jodafb)
Nominee.create!(user: lu, category: jodafb)
Nominee.create!(user: nixon, category: jodafb)
Nominee.create!(user: conco, category: trolfb)
Nominee.create!(user: fefe, category: trolfb)
Nominee.create!(user: jp, category: trolfb)
Nominee.create!(user: mds, category: calenton)
Nominee.create!(user: negri, category: calenton)
Nominee.create!(user: wilson, category: calenton)
Nominee.create!(user: conco, category: rustic)
Nominee.create!(user: tomy, category: rustic)
Nominee.create!(user: nixon, category: rustic)
Nominee.create!(user: luqui, category: lyric)
Nominee.create!(user: agulo, category: lyric)
Nominee.create!(user: jp, category: lyric)
Nominee.create!(user: seba, category: lyric)
Nominee.create!(user: nacho, category: wdj)
Nominee.create!(user: nixon, category: wdj)
Nominee.create!(user: mds, category: wdj)
Nominee.create!(user: lula, category: wdj)
Nominee.create!(user: fefe, category: fabuloso)
Nominee.create!(user: euge, category: fabuloso)
Nominee.create!(user: chino, category: fabuloso)
Nominee.create!(user: fagus, category: tribu)
Nominee.create!(user: agulo, category: tribu)
Nominee.create!(user: gabo, category: tribu)
Nominee.create!(user: inaki, category: tribu)
Nominee.create!(user: luqui, category: tribu)
Nominee.create!(user: conco, category: tribu)
Nominee.create!(user: fagus, category: ctaptc)
Nominee.create!(user: anita, category: police)
Nominee.create!(user: wilson, category: police)
Nominee.create!(user: wilson, category: malaonda)
Nominee.create!(user: mds, category: malaonda)
Nominee.create!(user: rampa, category: malaonda)
Nominee.create!(user: guido, category: malaonda)
Nominee.create!(user: gabo, category: bebu)
Nominee.create!(user: negri, category: bebu)
Nominee.create!(user: germu, category: bebu)
Nominee.create!(user: conco, category: conqueada)
Nominee.create!(user: tomy, category: conqueada)
Nominee.create!(user: euge, category: promiscuo)
Nominee.create!(user: capi, category: futbol)
Nominee.create!(user: jp, category: futbol)
Nominee.create!(user: conco, category: tl)
Nominee.create!(user: nixon, category: tl)
Nominee.create!(user: fefe, category: tl)
Nominee.create!(user: pol, category: tl)
Nominee.create!(user: ita, category: tl)
Nominee.create!(user: mds, category: tl)
Nominee.create!(user: bermu, category: fantasma)
Nominee.create!(user: mds, category: fantasma)
Nominee.create!(user: ninja, category: fantasma)
Nominee.create!(user: mati_a, category: fantasma)
Nominee.create!(user: conco, category: po)
Nominee.create!(user: nacho, category: po)
Nominee.create!(user: nixon, category: po)
Nominee.create!(user: lula, category: po)
Nominee.create!(user: rampa, category: po)
Nominee.create!(user: rampa, category: founder)
Nominee.create!(user: nixon, category: founder)
Nominee.create!(user: wilson, category: founder)
Nominee.create!(user: bermu, category: founder)
Nominee.create!(user: guido, category: founder)
Nominee.create!(user: lula, category: founder)
Nominee.create!(user: pol, category: founder)

Nominee.create!(user: buch, category: nuevo)
Nominee.create!(user: tylson, category: nuevo)
Nominee.create!(user: leo, category: nuevo)
Nominee.create!(user: gon, category: nuevo)
Nominee.create!(user: tedin, category: nuevo)
Nominee.create!(user: germu, category: nuevo)
Nominee.create!(user: fepo, category: nuevo)
Nominee.create!(user: negri, category: nuevo)
Nominee.create!(user: dinu, category: nuevo)
Nominee.create!(user: tomy, category: nuevo)
Nominee.create!(user: max, category: nuevo)
Nominee.create!(user: ranti, category: nuevo)
Nominee.create!(user: sola, category: nuevo)
Nominee.create!(user: lule, category: nuevo)
Nominee.create!(user: anita, category: nuevo)
Nominee.create!(user: ana, category: nuevo)
Nominee.create!(user: zannini, category: nuevo)
Nominee.create!(user: ferro, category: nuevo)
Nominee.create!(user: euge, category: nuevo)

puts 'done :)'